kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storm-crb
subjects:
  - kind: ServiceAccount
    name: storm
    namespace: default
roleRef:
  kind: ClusterRole
  name: storm-cluster-role
  apiGroup: rbac.authorization.k8s.io
